admissao/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from .views import ContratoSearchView, AvaliacaoFDMPViewSet, FormCandidatoCreateView, CandidatoUpdateView, FormFDMPFormCreateView, EscolasSearchView, FormFDMPUpdateView, ExcelImportView, CNPJSearchView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

router = DefaultRouter()
router.register(r'avaliacoes', AvaliacaoFDMPViewSet)

urlpatterns = [
    path("upload_template/", views.upload_template, name="upload_template"),
    path('fdmp/', CNPJSearchView.as_view(), name='buscar_cnpj'),
    path("form_fdmp/", FormFDMPFormCreateView.as_view(), name="form_fdmp"),
    path("form_fdmp_edit/<int:pk>/", FormFDMPUpdateView.as_view(), name="form_fdmp_edit"),
    path("busca_escolas/", EscolasSearchView.as_view(), name="busca_escolas"),
    path('importar_excel/', ExcelImportView.as_view(), name='importar_excel'),
    path("form_candidato/", FormCandidatoCreateView.as_view(), name="form_candidato"),
    path("busca_candidato/", ContratoSearchView.as_view(), name="busca_candidato"),
    path("candidato_edit/<int:pk>/", CandidatoUpdateView.as_view(), name="candidato_edit"),
    path("editar/<int:pk>/", views.select_contract_id, name="edit_candidato"),
    path('', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

projeto_maple/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


from usuarios.views import handler404

handler404 = "usuarios.views.handler404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("usuarios.urls")),
    path("", include("admissao.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admissao/models.py
from django.db import models
from usuarios.models import CustomUsuario
from num2words import num2words
from decimal import Decimal, ROUND_DOWN
# Create your views here.
class Base(models.Model):
    data_de_criacao = models.DateField("Data de Criação", auto_now_add=True)
    data_de_modificacao = models.DateField("Data de Modificação", auto_now=True)
    usuario_modificacao = models.ForeignKey(
        CustomUsuario, on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        abstract = True


YEAR_CHOICES = [
    ("2023", "2023"),
    ("2024", "2024"),
    ("2025", "2025"),
    ("2026", "2026"),
    ("2027", "2027"),
    ("2028", "2028"),
]

STATE_CHOICES = [
    ("AC", "Acre"),
    ("AL", "Alagoas"),
    ("AP", "Amapá"),
    ("AM", "Amazonas"),
    ("BA", "Bahia"),
    ("CE", "Ceará"),
    ("DF", "Distrito Federal"),
    ("ES", "Espírito Santo"),
    ("GO", "Goiás"),
    ("MA", "Maranhão"),
    ("MT", "Mato Grosso"),
    ("MS", "Mato Grosso do Sul"),
    ("MG", "Minas Gerais"),
    ("PA", "Pará"),
    ("PB", "Paraíba"),
    ("PR", "Paraná"),
    ("PE", "Pernambuco"),
    ("PI", "Piauí"),
    ("RJ", "Rio de Janeiro"),
    ("RN", "Rio Grande do Norte"),
    ("RS", "Rio Grande do Sul"),
    ("RO", "Rondônia"),
    ("RR", "Roraima"),
    ("SC", "Santa Catarina"),
    ("SP", "São Paulo"),
    ("SE", "Sergipe"),
    ("TO", "Tocantins"),
]

MARITAL_STATUS_CHOICES = [
    ("solteiro", "Solteiro(a)"),
    ("casado", "Casado(a)"),
    ("divorciado", "Divorciado(a)"),
    ("viuvo", "Viúvo(a)"),
    ("separado", "Separado(a)"),
    ("uniao_estavel", "Em União Estável"),
]


class Templates(Base):
    name = models.CharField(max_length=200)
    file = models.FileField(upload_to="contract_templates/")
    ano_vigencia = models.CharField(max_length=4, choices=YEAR_CHOICES)

    def __str__(self):
        return f"{self.name}"

def formatar_valor(valor):
    # Converte para Decimal para manter precisão
    valor_decimal = Decimal(valor)
    # Formata com separadores de milhar e duas casas decimais
    # Usando quantize para evitar arredondamento indesejado
    valor_formatado = valor_decimal.quantize(Decimal("1.00"), rounding=ROUND_DOWN)
    # Formata com o padrão brasileiro de milhar e decimal
    return "{:,.2f}".format(valor_formatado).replace(",", "X").replace(".", ",").replace("X", ".")


def numero_por_extenso(valor, moeda='real'):
    valor_inteiro = int(valor)
    centavos = int((valor - valor_inteiro) * 100)
    texto = num2words(valor_inteiro, lang='pt_BR')
    
    if moeda == 'dolar':
        texto += " dólares" if valor_inteiro > 1 else " dólar"
    else:
        texto += " reais" if valor_inteiro > 1 else " real"
    
    if centavos > 0:
        texto += " e " + num2words(centavos, lang='pt_BR')
        texto += " centavos"
    
    return texto.capitalize()


class Contrato(Base):
    nome = models.CharField(max_length=200)
    cpf = models.CharField(max_length=14)
    rg = models.CharField(max_length=20)
    nascionalidade = models.CharField(max_length=200)
    estado_civil = models.CharField(max_length=200, choices=MARITAL_STATUS_CHOICES)
    email = models.EmailField()
    data_de_recebimento_da_oferta = models.DateField(null=True, blank=True)
    uf_pretendido = models.CharField(max_length=2, choices=STATE_CHOICES, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    dias_vigencia = models.IntegerField(null=True, blank=True)
    data_de_inicio_contrato = models.DateField(null=True, blank=True)
    data_do_fim_contrato = models.DateField(null=True, blank=True)
    taxa_inicial_franquia = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True)
    cambio_valor = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True)
    cambio_data = models.DateField(null=True, blank=True)
    data_de_assinatura = models.DateField(null=True, blank=True)
    outros = models.CharField(max_length=25000, null=True, blank=True)
    endereco = models.CharField(max_length=550)
    numero = models.CharField(max_length=250)
    complemento = models.CharField(max_length=250)
    bairro = models.CharField(max_length=250)
    cidade_endereco = models.CharField(max_length=250)
    uf_endereco = models.CharField(max_length=2, choices=STATE_CHOICES)
    cep = models.CharField(max_length=9)

    def __str__(self):
        return f"{self.nome}"

    def get_field_values(self):
        dias_por_extenso = num2words(self.dias_vigencia, lang='pt_BR')
        valor_dolar_extenso = numero_por_extenso(self.taxa_inicial_franquia, 'dolar')
        total_pagamento = self.cambio_valor * self.taxa_inicial_franquia
        total_pagamento_formatado = formatar_valor(total_pagamento)
        total_pagamento_extenso = numero_por_extenso(total_pagamento, 'real')
        taxa_inicial_franquia_formatado = formatar_valor(self.taxa_inicial_franquia)
        cambio_valor_formatado = formatar_valor(self.cambio_valor)
        cambio_valor_extenso = numero_por_extenso(self.cambio_valor, 'real')
        
        return {
            "{nome}": self.nome,
            "{cpf}": self.cpf,
            "{rg}": self.rg,
            "{nascionalidade}": self.nascionalidade,
            "{estado_civil}": self.estado_civil,
            "{email}": self.email,
            "{data_de_recebimento_da_oferta}": (
                self.data_de_recebimento_da_oferta.strftime("%d/%m/%Y")
                if self.data_de_recebimento_da_oferta
                else ""
            ),
            "{uf_pretendido}": self.uf_pretendido,
            "{cidade}": self.cidade,
            "{dias_vigencia}": self.dias_vigencia,
            "{dias_por_extenso}": dias_por_extenso,
            "{data_de_inicio_contrato}": (
                self.data_de_inicio_contrato.strftime("%d/%m/%Y")
                if self.data_de_inicio_contrato
                else ""
            ),
            "{data_do_fim_contrato}": (
                self.data_do_fim_contrato.strftime("%d/%m/%Y")
                if self.data_do_fim_contrato
                else ""
            ),
            "{taxa_inicial_franquia}": taxa_inicial_franquia_formatado,
            "{valor_dolar_extenso}": valor_dolar_extenso,
            "{total_a_ser_pago}": total_pagamento_formatado,
            "{total_pagamento_extenso}": total_pagamento_extenso,
            "{cambio_valor}": cambio_valor_formatado,
            "{cambio_valor_extenso}": cambio_valor_extenso,
            "{cambio_data}": (
                self.cambio_data.strftime("%d/%m/%Y") if self.cambio_data else ""
            ),
            "{data_de_assinatura}": (
                self.data_de_assinatura.strftime("%d/%m/%Y")
                if self.data_de_assinatura
                else ""
            ),
            "{outros}": self.outros,
            "{endereco}": self.endereco,
            "{numero}": self.numero,
            "{complemento}": self.complemento,
            "{bairro}": self.bairro,
            "{cidade_endereco}": self.cidade_endereco,
            "{uf_endereco}": self.uf_endereco,
            "{cep}": self.cep,
        }



class AvaliacaoFDMP(models.Model):
    cnpj = models.CharField(max_length=18, verbose_name=("CNPJ"))
    razao_social = models.CharField(max_length=200, verbose_name=("Razão Social"))
    nome = models.CharField(max_length=200, verbose_name=("Nome"))
    cpf = models.CharField(max_length=14, verbose_name=("CPF"))
    cargo = models.CharField(max_length=200, null=True, blank=True, verbose_name=("Cargo"))
    uf = models.CharField(max_length=2, choices=STATE_CHOICES, verbose_name=("UF"))
    cidade = models.CharField(max_length=100, verbose_name=("Cidade"))
    bear_care_qtd = models.IntegerField(null=True, blank=True, default=0, verbose_name=("Bear Care - Quantidade de Alunos"))
    bear_care_vm = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True, default=0, verbose_name=("Bear Care - Valor Médio da Mensalidade"))
    toddler_qtd = models.IntegerField(null=True, blank=True, default=0, verbose_name=("Toddler - Quantidade de Alunos"))
    toddler_vm = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True, default=0, verbose_name=("Toddler - Valor Médio da Mensalidade"))
    nursery_qtd = models.IntegerField(null=True, blank=True, default=0, verbose_name=("Nursery - Quantidade de Alunos"))
    nursery_vm = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True, default=0, verbose_name=("Nursery - Valor Médio da Mensalidade"))
    junior_kindergarten_qtd = models.IntegerField(null=True, blank=True, default=0, verbose_name=("Junior Kindergarten - Quantidade de Alunos"))
    junior_kindergarten_vm = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True, default=0, verbose_name=("Junior Kindergarten - Valor Médio da Mensalidade"))
    senior_kindergarten_qtd = models.IntegerField(null=True, blank=True, default=0, verbose_name=("Senior Kindergarten - Quantidade de Alunos"))
    senior_kindergarten_vm = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True, default=0, verbose_name=("Senior Kindergarten - Valor Médio da Mensalidade"))
    year_1_qtd = models.IntegerField(null=True, blank=True, default=0, verbose_name=("Year 1 - Quantidade de Alunos"))
    year_1_vm = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True, default=0, verbose_name=("Year 1 - Valor Médio da Mensalidade"))
    year_2_qtd = models.IntegerField(null=True, blank=True, default=0, verbose_name=("Year 2 - Quantidade de Alunos"))
    year_2_vm = models.DecimalField(max_digits=25, decimal_places=2, null=True, blank=True, default=0, verbose_name=("Year 2 - Valor Médio da Mensalidade"))

templates/admissao/busca_de_candidatos.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Bootstrap, Landing page, Template, Registration, Landing">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Grayrids">
    <title>Maple Bear</title>

    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets_2/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/nivo-lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/color-switcher.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/menu_sideslide.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/main.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/formulario.css' %}">    
    <link rel="stylesheet" href="{% static 'assets_2/css/responsive.css' %}">
    <link rel="icon" type="image/png" href="{% static 'assets_2/img/maple_bear.svg' %}">
    <link id="pagestyle" href="{% static 'css/busca.css' %}" rel="stylesheet" />
    <link id="pagestyle" href="{% static 'css/paginacao.css' %}" rel="stylesheet" />
  </head>
  
  <body>
    <!-- Header Section Start -->
    <header id="slider-area">  
      <nav class="navbar navbar-expand-md fixed-top scrolling-navbar bg-white">
        <div class="container">  
          <a class="navbar-brand" href="{% url 'index' %}"><img  src="{% static 'assets_2/img/maple_bear.svg' %}" alt="" style="max-height: 40px;">  Maple Bear</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="lni-menu"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto w-100 justify-content-end">
              
              <li class="nav-item">
                <a class="nav-link page-scroll" href="{% url 'index' %}">Home</a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link page-scroll nav-link-ded dropdown-toggle" id="dropdownContratos" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contratos</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="min-width: 200px;">
                  <a class="nav-link" href="{% url 'busca_candidato' %}">Buscar Candidatos</a>
                  <a class="nav-link" href="{% url 'form_candidato' %}">Formulário PCF</a>
                  <a class="nav-link" href="{% url 'upload_template' %}">Importar Modelo de Contrato</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link page-scroll nav-link-ded dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escolas</a>
                <div class="dropdown-menu" style="min-width: 200px;">
                  <a class="nav-link" href="{% url 'busca_escolas' %}">Buscar Escolas</a>
                  <a class="nav-link" href="{% url 'form_fdmp' %}">Formulário FDMP</a>
                </div>
              </li>


              {% if user.is_anonymous %}
              {% else %}
              <li class="nav-item">
                <a class="nav-link page-scroll" href="{% url 'logout' %}">Sair</a>
              </li>
              {% endif %}  

            </ul>              
          </div>
        </div>
      </nav>  


    </header>
    <!-- Header Section End --> 


      
    <!-- Features Section Start -->
    <section id="busca" class="section">
      <div class="container">
        <div class="section-header">          
          <h2 class="section-title">BUSQUE O CANDIDATO:</h2>
          <span>CANDIDATURAS</span>
        </div>
        <div class="row">
          <div class="row text-center py-2 mt-3">
            <div class="col-4 mx-auto">
                <div class="input-group input-group-dynamic mb-4" >
                    <span class="input-group-text"><i class="fas fa-search" aria-hidden="true"></i></span>
                    <form method="GET" action="" class="w-100" >
                        <input id="search-input" class="form-control custom-input" type="text" name="q" placeholder="Buscar por CPF">
                        <input class="form-control" type="submit" placeholder="Buscar" style="display: none;">
                    </form>
                </div>
            </div>
          </div>




          <table class="table">
            <thead>
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">E-mail</th>
                <th scope="col">Editar</th>

              </tr>
            </thead>
            <tbody>
              {% for contrato in object_list %}
                <tr>
                  <td>
                    <a href="{% url 'edit_candidato' contrato.id %}">{{ contrato.nome }}</a>
                  </td>
                  <td>
                    <p>{{ contrato.cpf }}</p>
                  </td>
                  <td>
                    <p>{{ contrato.email }}</p>
                  </td>
                  <td>
                    <a href="{% url 'form_fdmp_edit' contrato.id %}">
                      <i class="fa fa-pencil-square-o"></i>
                    </a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    
        <!-- Início da Paginação -->
        <div class="row text-center py-2">
          <div class="col-4 mx-auto">
              <ul class="pagination pagination-primary m-4">
                  <!-- Se tem página anterior -->
                  {% if page_obj.object_list|length > 0 %}
                  {% if page_obj.has_previous %}
                      <li class="page-item">
                          <a class="page-link" href="?page=1&q={{ q }}&order_by={{ order_by }}" aria-label="Previous">
                              <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                          </a>
                      </li>
                  {% endif %}
                  <!-- Loop para exibir os números das páginas -->
                  {% for i in page_range %}
                      {% if page_obj.number == i %}
                          <li class="page-item active">
                              <a class="page-link active-link" href="#">{{ i }}</a>
                          </li>
                      {% else %}
                          <li class="page-item">
                              <a class="page-link" href="?page={{ i }}&q={{ q }}&order_by={{ order_by }}">{{ i }}</a>
                          </li>
                      {% endif %}
                  {% endfor %}
                  <!-- Se tem próxima página -->
                  {% if page_obj.has_next %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&q={{ q }}&order_by={{ order_by }}" aria-label="Next">
                              <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                          </a>
                      </li>
                  {% endif %}
                  {% endif %}
          </div>
        </div>
        </div>
      </div>
    </section>
    </div>
    <!-- Features Section End -->   















    
     

    </footer>
    <!-- Footer Section End --> 

    <!-- Go To Top Link -->
    <a href="#" class="back-to-top">
      <i class="lni-arrow-up"></i>
    </a>

    <div id="loader">
      <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
      </div>
    </div>    

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_cliente_gi').change(function () {
                let cliente_gi_id = $(this).val();
                $.get('/api/departamentos/?cliente_gi_id=' + cliente_gi_id, function (data) {
                    let select = $('#id_departamento');
                    select.empty();
                    select.append('<option value="" selected>---------</option>'); // Adicionado aqui
                    $.each(data, function (index, value) {
                        select.append('<option value="' + value.id + '">' + value.nome_departamento + '</option>');
                    });
                });
                $.get('/api/bases/?cliente_gi_id=' + cliente_gi_id, function (data) {
                    let select = $('#id_cargo');
                    select.empty();
                    select.append('<option value="" selected>---------</option>'); // Adicionado aqui
                    $.each(data, function (index, value) {
                        select.append('<option value="' + value.id + '">' + value.cargo + '</option>');
                    });
                });
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            $('#id_departamento').change(function() {
                var departamento_id = $(this).val();
                $.getJSON('/api/turnos/?departamento_id=' + departamento_id, function(data) {
                    var select = $('#id_turno');
                    select.empty();
                    select.append('<option value="" selected>---------</option>'); // Adicionado aqui
                    $.each(data, function(index, value) {
                        select.append('<option value="' + value.id + '">' + value.nome + '</option>');
                    });
                });
            });
        });
    </script>
    <script src="{% static 'assets_2/js/jquery-min.js' %}"></script>
    <script src="{% static 'assets_2/js/popper.min.js' %}"></script>
    <script src="{% static 'assets_2/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets_2/js/classie.js' %}"></script>
    <script src="{% static 'assets_2/js/color-switcher.js' %}"></script>
    <script src="{% static 'assets_2/js/jquery.mixitup.js' %}"></script>
    <script src="{% static 'assets_2/js/nivo-lightbox.js' %}"></script>
    <script src="{% static 'assets_2/js/owl.carousel.js' %}"></script>    
    <script src="{% static 'assets_2/js/jquery.stellar.min.js' %}"></script>    
    <script src="{% static 'assets_2/js/jquery.nav.js' %}"></script>    
    <script src="{% static 'assets_2/js/scrolling-nav.js' %}"></script>    
    <script src="{% static 'assets_2/js/jquery.easing.min.js' %}"></script>     
    <script src="{% static 'assets_2/js/wow.js' %}"></script> 
    <script src="{% static 'assets_2/js/jquery.vide.js' %}"></script>
    <script src="{% static 'assets_2/js/jquery.counterup.min.js' %}"></script>    
    <script src="{% static 'assets_2/js/jquery.magnific-popup.min.js' %}"></script>    
    <script src="{% static 'assets_2/js/waypoints.min.js' %}"></script>    
    <script src="{% static 'assets_2/js/form-validator.min.js' %}"></script>
    <script src="{% static 'assets_2/js/contact-form-script.js' %}"></script>   
    <script src="{% static 'assets_2/js/main.js' %}"></script>
    <script>
      window.STATIC_URL = "{% static '' %}";
    </script>
    <script>
      document.getElementById('search-input').addEventListener('focus', function() {
          this.style.border = 'none';
      });
      document.getElementById('search-input').addEventListener('blur', function() {
          this.style.border = '';  // Restaure a borda quando o elemento perde o foco
      });
      </script>
  </body>
</html>

templates/admissao/select_contract.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <select name="collaborator">
            {% for collaborator in collaborators %}
            <option value="{{ collaborator.id }}">{{ collaborator.name }}</option>
            {% endfor %}
        </select>
        <select name="template">
            {% for template in templates %}
            <option value="{{ template.id }}">{{ template.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Generate contract</button>
    </form> 
</body>
</html>

templates/admissao/upload_excel.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Bootstrap, Landing page, Template, Registration, Landing">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Grayrids">
    <title>Maple Bear</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets_2/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/nivo-lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/color-switcher.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/menu_sideslide.css' %}">
    <link rel="stylesheet" href="{% static 'assets_2/css/main.css' %}"> 
    <link rel="stylesheet" href="{% static 'assets_2/css/responsive.css' %}">
    <link id="pagestyle" href="{% static 'css/upload_files.css' %}" rel="stylesheet" />
    <link rel="icon" type="image/png" href="{% static 'assets_2/img/maple_bear.svg' %}">
  </head>
  
  <body>
    <!-- Header Section Start -->
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file" name="excel_file">
      <button type="submit">Importar</button>
  </form>
  
  </body>
</html>